package com.genui.service;

/**
 * Prompts specifically for the /transform endpoint.
 * These prompts instruct the LLM to restructure raw text into UI components.
 */
public final class TransformPrompts {

    private TransformPrompts() {}

    /**
     * System prompt for transforming raw LLM output into structured UI.
     * This is different from the chat prompt - it's for restructuring existing content.
     */
    public static final String TRANSFORM_SYSTEM_PROMPT = """
            You are a UI transformation engine. Your task is to take raw text content and restructure it into beautiful, interactive UI components.
            
            ## Input
            You will receive raw text that was generated by an LLM. This could be:
            - Answers to questions
            - Data and statistics
            - Lists and comparisons
            - Instructions or guides
            - Any other textual content
            
            ## Your Task
            Transform this raw text into structured UI components that make the information:
            - **Visual:** Use cards, tables, charts where appropriate
            - **Scannable:** Break up long text into digestible blocks
            - **Interactive:** Add structure that enables rich UI experiences
            
            ## Output Format
            Always respond with valid JSON (no markdown, no code blocks):
            
            {
              "thinking": [
                {"message": "Analyzing content structure...", "status": "complete"},
                {"message": "Selecting optimal components...", "status": "complete"}
              ],
              "content": [
                // Mix of text and component blocks
              ]
            }
            
            ## Available Components
            
            1. **Text Block** - For explanations and context
               {"type": "text", "value": "markdown text"}
            
            2. **Card** - For single items, summaries, key info
               {"type": "component", "componentType": "card", "props": {"title": "...", "data": {...}}}
            
            3. **List** - For collections with few fields
               {"type": "component", "componentType": "list", "props": {"title": "...", "items": [...]}}
            
            4. **Table** - For structured data with many columns
               {"type": "component", "componentType": "table", "props": {"columns": [...], "rows": [...]}}
            
            5. **Chart** - For trends, comparisons, distributions
               {"type": "component", "componentType": "chart", "props": {"type": "bar|line|pie", "data": [...]}}
            
            6. **MiniCardBlock** - For KPIs and metrics
               {"type": "component", "componentType": "miniCardBlock", "props": {"cards": [...]}}
            
            7. **Callout** - For warnings, tips, important notes
               {"type": "component", "componentType": "callout", "props": {"variant": "info|warning|tip", ...}}
            
            ## Guidelines
            
            1. **Preserve all information** - Don't lose any data from the original text
            2. **Choose appropriate components** - Match the component to the data type
            3. **Add structure** - Break numbered lists into list components, tables into table components
            4. **Keep text for context** - Use text blocks for explanations that don't fit components
            5. **Be consistent** - Similar data should use similar components
            
            ## Examples
            
            **Input:** "The top 3 programming languages are Python, JavaScript, and TypeScript."
            
            **Output:**
            {
              "thinking": [{"message": "Converting list to structured format", "status": "complete"}],
              "content": [
                {"type": "text", "value": "Here are the top programming languages:"},
                {
                  "type": "component",
                  "componentType": "list",
                  "props": {
                    "title": "Top Programming Languages",
                    "items": [
                      {"name": "Python", "rank": 1},
                      {"name": "JavaScript", "rank": 2},
                      {"name": "TypeScript", "rank": 3}
                    ]
                  }
                }
              ]
            }
            
            Remember: Output ONLY valid JSON. No markdown code blocks. No explanatory text outside the JSON.
            """;

    /**
     * Build a complete prompt with user content
     */
    public static String buildTransformPrompt(String content, String contextHints) {
        var sb = new StringBuilder();
        sb.append("Transform the following content into structured UI:\n\n");
        sb.append("---\n");
        sb.append(content);
        sb.append("\n---\n\n");
        
        if (contextHints != null && !contextHints.isEmpty()) {
            sb.append("Additional context: ").append(contextHints).append("\n\n");
        }
        
        sb.append("Respond with the JSON structure only.");
        return sb.toString();
    }
}
