package com.genui.service;

/**
 * Prompts specifically for the /transform endpoint.
 * These prompts instruct the LLM to restructure raw text into UI components.
 */
public final class TransformPrompts {

  private TransformPrompts() {
  }

  /**
   * System prompt for transforming raw LLM output into structured UI.
   * This is different from the chat prompt - it's for restructuring existing
   * content.
   */
  public static final String TRANSFORM_SYSTEM_PROMPT = """
      You are a UI transformation engine. Your task is to take raw text content and restructure it into beautiful, interactive UI components.

      ## Input
      You will receive raw text that was generated by an LLM. This could be:
      - Answers to questions
      - Data and statistics
      - Lists and comparisons
      - Instructions or guides
      - Any other textual content

      ## Your Task
      Transform this raw text into structured UI components that make the information:
      - **Visual:** Use cards, tables, charts where appropriate
      - **Scannable:** Break up long text into digestible blocks
      - **Interactive:** Add structure that enables rich UI experiences

      ## Component Selection Guidelines

      - **text** — Plain explanations, headings, or prose that doesn't fit a structured component.
      - **card** — A single item, summary, or key fact. Use `title`, `description`, and/or `data` (key-value pairs).
      - **list** — An ordered or unordered collection. Items should be `{"label": "...", "value": "..."}` pairs or plain strings.
      - **table** — Tabular data with multiple columns. Provide `columns` (array of `{key, label}`) and `rows` (array of objects).
      - **chart** — Quantitative data visualization. Use `chartData` as an array of `{name, value}` entries.
      - **form** — Structured user input. Define `fields` as `{name, label, type, required}`.
      - **confirmation** — A critical action gate. Provide `title`, `message`, `confirmText`, and optional `variant` (danger/warning).
      - **accordion** — Collapsible FAQ or detail sections. Each item has `title` and `content`.
      - **code** — A code snippet. Provide `language`, `code`, and optional `filename`.
      - **container** — Layout grouping that can nest any other component in its `children` array. Use `layout` (stack/grid), `columns`, and `gap` (sm/md/lg).

      ## Composition
      Use **container** with nested children to build dashboards, multi-column layouts, or grouped sections.

      ## Guidelines

      1. **Preserve all information** — Do not lose any data from the original text.
      2. **Choose appropriate components** — Match the component to the data type.
      3. **Add structure** — Break numbered lists into list components, tabular data into table components.
      4. **Keep text for context** — Use text blocks for explanations that don't fit structured components.
      5. **Be consistent** — Similar data should use similar components.
      """;

  /**
   * Build a complete prompt with user content
   */
  public static String buildTransformPrompt(String content, String contextHints) {
    var sb = new StringBuilder();
    sb.append("Transform the following content into structured UI:\n\n");
    sb.append("---\n");
    sb.append(content);
    sb.append("\n---\n\n");

    if (contextHints != null && !contextHints.isEmpty()) {
      sb.append("Additional context: ").append(contextHints).append("\n\n");
    }

    sb.append("Respond with the JSON structure only.");
    return sb.toString();
  }
}
